/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedWatchlistsRouteImport } from './routes/_authenticated/watchlists'
import { Route as AuthenticatedStealthRouteImport } from './routes/_authenticated/stealth'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedProxiesRouteImport } from './routes/_authenticated/proxies'
import { Route as AuthenticatedProfileUpdaterRouteImport } from './routes/_authenticated/profile-updater'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedJoinPacingRouteImport } from './routes/_authenticated/join-pacing'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCleanupRouteImport } from './routes/_authenticated/cleanup'
import { Route as AuthenticatedCaptchaRouteImport } from './routes/_authenticated/captcha'
import { Route as AuthenticatedBulkPlusRouteImport } from './routes/_authenticated/bulk-plus'
import { Route as AuthenticatedBulkMixRouteImport } from './routes/_authenticated/bulk-mix'
import { Route as AuthenticatedBotSuccessRouteImport } from './routes/_authenticated/bot-success'
import { Route as AuthenticatedBotFlowRouteImport } from './routes/_authenticated/bot-flow'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedActionsRouteImport } from './routes/_authenticated/actions'
import { Route as ApiPublicCleanupStreamRouteImport } from './routes/api/public/cleanup-stream'
import { Route as ApiPublicBulkStreamRouteImport } from './routes/api/public/bulk-stream'
import { Route as ApiPublicActionsStreamRouteImport } from './routes/api/public/actions-stream'
import { Route as AuthenticatedTasksNewRouteImport } from './routes/_authenticated/tasks.new'
import { Route as AuthenticatedTasksIdRouteImport } from './routes/_authenticated/tasks.$id'
import { Route as AuthenticatedGroupsIdRouteImport } from './routes/_authenticated/groups.$id'
import { Route as AuthenticatedAccountsIdRouteImport } from './routes/_authenticated/accounts.$id'
import { Route as ApiPublicMiniappProxySplatRouteImport } from './routes/api/public/miniapp-proxy.$'
import { Route as ApiPublicHooksRunScheduledBroadcastsRouteImport } from './routes/api/public/hooks/run-scheduled-broadcasts'
import { Route as ApiPublicHooksRetentionRouteImport } from './routes/api/public/hooks/retention'
import { Route as ApiPublicHooksResumeStuckRouteImport } from './routes/api/public/hooks/resume-stuck'
import { Route as ApiPublicHooksDailySummaryRouteImport } from './routes/api/public/hooks/daily-summary'
import { Route as ApiPublicHooksAutoLeaveRouteImport } from './routes/api/public/hooks/auto-leave'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchlistsRoute = AuthenticatedWatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStealthRoute = AuthenticatedStealthRouteImport.update({
  id: '/stealth',
  path: '/stealth',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProxiesRoute = AuthenticatedProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileUpdaterRoute =
  AuthenticatedProfileUpdaterRouteImport.update({
    id: '/profile-updater',
    path: '/profile-updater',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoinPacingRoute = AuthenticatedJoinPacingRouteImport.update({
  id: '/join-pacing',
  path: '/join-pacing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCleanupRoute = AuthenticatedCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaptchaRoute = AuthenticatedCaptchaRouteImport.update({
  id: '/captcha',
  path: '/captcha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBulkPlusRoute = AuthenticatedBulkPlusRouteImport.update({
  id: '/bulk-plus',
  path: '/bulk-plus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBulkMixRoute = AuthenticatedBulkMixRouteImport.update({
  id: '/bulk-mix',
  path: '/bulk-mix',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotSuccessRoute = AuthenticatedBotSuccessRouteImport.update({
  id: '/bot-success',
  path: '/bot-success',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotFlowRoute = AuthenticatedBotFlowRouteImport.update({
  id: '/bot-flow',
  path: '/bot-flow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActionsRoute = AuthenticatedActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCleanupStreamRoute = ApiPublicCleanupStreamRouteImport.update({
  id: '/api/public/cleanup-stream',
  path: '/api/public/cleanup-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBulkStreamRoute = ApiPublicBulkStreamRouteImport.update({
  id: '/api/public/bulk-stream',
  path: '/api/public/bulk-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicActionsStreamRoute = ApiPublicActionsStreamRouteImport.update({
  id: '/api/public/actions-stream',
  path: '/api/public/actions-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksNewRoute = AuthenticatedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIdRoute = AuthenticatedTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsIdRoute = AuthenticatedGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsIdRoute = AuthenticatedAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMiniappProxySplatRoute =
  ApiPublicMiniappProxySplatRouteImport.update({
    id: '/api/public/miniapp-proxy/$',
    path: '/api/public/miniapp-proxy/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunScheduledBroadcastsRoute =
  ApiPublicHooksRunScheduledBroadcastsRouteImport.update({
    id: '/api/public/hooks/run-scheduled-broadcasts',
    path: '/api/public/hooks/run-scheduled-broadcasts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRetentionRoute = ApiPublicHooksRetentionRouteImport.update({
  id: '/api/public/hooks/retention',
  path: '/api/public/hooks/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksResumeStuckRoute =
  ApiPublicHooksResumeStuckRouteImport.update({
    id: '/api/public/hooks/resume-stuck',
    path: '/api/public/hooks/resume-stuck',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailySummaryRoute =
  ApiPublicHooksDailySummaryRouteImport.update({
    id: '/api/public/hooks/daily-summary',
    path: '/api/public/hooks/daily-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoLeaveRoute = ApiPublicHooksAutoLeaveRouteImport.update({
  id: '/api/public/hooks/auto-leave',
  path: '/api/public/hooks/auto-leave',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bot-flow': typeof AuthenticatedBotFlowRoute
  '/bot-success': typeof AuthenticatedBotSuccessRoute
  '/bulk-mix': typeof AuthenticatedBulkMixRoute
  '/bulk-plus': typeof AuthenticatedBulkPlusRoute
  '/captcha': typeof AuthenticatedCaptchaRoute
  '/cleanup': typeof AuthenticatedCleanupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health': typeof AuthenticatedHealthRoute
  '/join-pacing': typeof AuthenticatedJoinPacingRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/profile-updater': typeof AuthenticatedProfileUpdaterRoute
  '/proxies': typeof AuthenticatedProxiesRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/report': typeof AuthenticatedReportRoute
  '/search': typeof AuthenticatedSearchRoute
  '/stealth': typeof AuthenticatedStealthRoute
  '/watchlists': typeof AuthenticatedWatchlistsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/api/public/actions-stream': typeof ApiPublicActionsStreamRoute
  '/api/public/bulk-stream': typeof ApiPublicBulkStreamRoute
  '/api/public/cleanup-stream': typeof ApiPublicCleanupStreamRoute
  '/api/public/hooks/auto-leave': typeof ApiPublicHooksAutoLeaveRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/hooks/resume-stuck': typeof ApiPublicHooksResumeStuckRoute
  '/api/public/hooks/retention': typeof ApiPublicHooksRetentionRoute
  '/api/public/hooks/run-scheduled-broadcasts': typeof ApiPublicHooksRunScheduledBroadcastsRoute
  '/api/public/miniapp-proxy/$': typeof ApiPublicMiniappProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bot-flow': typeof AuthenticatedBotFlowRoute
  '/bot-success': typeof AuthenticatedBotSuccessRoute
  '/bulk-mix': typeof AuthenticatedBulkMixRoute
  '/bulk-plus': typeof AuthenticatedBulkPlusRoute
  '/captcha': typeof AuthenticatedCaptchaRoute
  '/cleanup': typeof AuthenticatedCleanupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health': typeof AuthenticatedHealthRoute
  '/join-pacing': typeof AuthenticatedJoinPacingRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/profile-updater': typeof AuthenticatedProfileUpdaterRoute
  '/proxies': typeof AuthenticatedProxiesRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/report': typeof AuthenticatedReportRoute
  '/search': typeof AuthenticatedSearchRoute
  '/stealth': typeof AuthenticatedStealthRoute
  '/watchlists': typeof AuthenticatedWatchlistsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/api/public/actions-stream': typeof ApiPublicActionsStreamRoute
  '/api/public/bulk-stream': typeof ApiPublicBulkStreamRoute
  '/api/public/cleanup-stream': typeof ApiPublicCleanupStreamRoute
  '/api/public/hooks/auto-leave': typeof ApiPublicHooksAutoLeaveRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/hooks/resume-stuck': typeof ApiPublicHooksResumeStuckRoute
  '/api/public/hooks/retention': typeof ApiPublicHooksRetentionRoute
  '/api/public/hooks/run-scheduled-broadcasts': typeof ApiPublicHooksRunScheduledBroadcastsRoute
  '/api/public/miniapp-proxy/$': typeof ApiPublicMiniappProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/actions': typeof AuthenticatedActionsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bot-flow': typeof AuthenticatedBotFlowRoute
  '/_authenticated/bot-success': typeof AuthenticatedBotSuccessRoute
  '/_authenticated/bulk-mix': typeof AuthenticatedBulkMixRoute
  '/_authenticated/bulk-plus': typeof AuthenticatedBulkPlusRoute
  '/_authenticated/captcha': typeof AuthenticatedCaptchaRoute
  '/_authenticated/cleanup': typeof AuthenticatedCleanupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/join-pacing': typeof AuthenticatedJoinPacingRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/_authenticated/profile-updater': typeof AuthenticatedProfileUpdaterRoute
  '/_authenticated/proxies': typeof AuthenticatedProxiesRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/stealth': typeof AuthenticatedStealthRoute
  '/_authenticated/watchlists': typeof AuthenticatedWatchlistsRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/_authenticated/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/_authenticated/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/_authenticated/tasks/new': typeof AuthenticatedTasksNewRoute
  '/api/public/actions-stream': typeof ApiPublicActionsStreamRoute
  '/api/public/bulk-stream': typeof ApiPublicBulkStreamRoute
  '/api/public/cleanup-stream': typeof ApiPublicCleanupStreamRoute
  '/api/public/hooks/auto-leave': typeof ApiPublicHooksAutoLeaveRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/hooks/resume-stuck': typeof ApiPublicHooksResumeStuckRoute
  '/api/public/hooks/retention': typeof ApiPublicHooksRetentionRoute
  '/api/public/hooks/run-scheduled-broadcasts': typeof ApiPublicHooksRunScheduledBroadcastsRoute
  '/api/public/miniapp-proxy/$': typeof ApiPublicMiniappProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/actions'
    | '/analytics'
    | '/bot-flow'
    | '/bot-success'
    | '/bulk-mix'
    | '/bulk-plus'
    | '/captcha'
    | '/cleanup'
    | '/dashboard'
    | '/health'
    | '/join-pacing'
    | '/owner'
    | '/profile-updater'
    | '/proxies'
    | '/recipes'
    | '/referrals'
    | '/report'
    | '/search'
    | '/stealth'
    | '/watchlists'
    | '/workspace'
    | '/accounts/$id'
    | '/groups/$id'
    | '/tasks/$id'
    | '/tasks/new'
    | '/api/public/actions-stream'
    | '/api/public/bulk-stream'
    | '/api/public/cleanup-stream'
    | '/api/public/hooks/auto-leave'
    | '/api/public/hooks/daily-summary'
    | '/api/public/hooks/resume-stuck'
    | '/api/public/hooks/retention'
    | '/api/public/hooks/run-scheduled-broadcasts'
    | '/api/public/miniapp-proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/actions'
    | '/analytics'
    | '/bot-flow'
    | '/bot-success'
    | '/bulk-mix'
    | '/bulk-plus'
    | '/captcha'
    | '/cleanup'
    | '/dashboard'
    | '/health'
    | '/join-pacing'
    | '/owner'
    | '/profile-updater'
    | '/proxies'
    | '/recipes'
    | '/referrals'
    | '/report'
    | '/search'
    | '/stealth'
    | '/watchlists'
    | '/workspace'
    | '/accounts/$id'
    | '/groups/$id'
    | '/tasks/$id'
    | '/tasks/new'
    | '/api/public/actions-stream'
    | '/api/public/bulk-stream'
    | '/api/public/cleanup-stream'
    | '/api/public/hooks/auto-leave'
    | '/api/public/hooks/daily-summary'
    | '/api/public/hooks/resume-stuck'
    | '/api/public/hooks/retention'
    | '/api/public/hooks/run-scheduled-broadcasts'
    | '/api/public/miniapp-proxy/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/actions'
    | '/_authenticated/analytics'
    | '/_authenticated/bot-flow'
    | '/_authenticated/bot-success'
    | '/_authenticated/bulk-mix'
    | '/_authenticated/bulk-plus'
    | '/_authenticated/captcha'
    | '/_authenticated/cleanup'
    | '/_authenticated/dashboard'
    | '/_authenticated/health'
    | '/_authenticated/join-pacing'
    | '/_authenticated/owner'
    | '/_authenticated/profile-updater'
    | '/_authenticated/proxies'
    | '/_authenticated/recipes'
    | '/_authenticated/referrals'
    | '/_authenticated/report'
    | '/_authenticated/search'
    | '/_authenticated/stealth'
    | '/_authenticated/watchlists'
    | '/_authenticated/workspace'
    | '/_authenticated/accounts/$id'
    | '/_authenticated/groups/$id'
    | '/_authenticated/tasks/$id'
    | '/_authenticated/tasks/new'
    | '/api/public/actions-stream'
    | '/api/public/bulk-stream'
    | '/api/public/cleanup-stream'
    | '/api/public/hooks/auto-leave'
    | '/api/public/hooks/daily-summary'
    | '/api/public/hooks/resume-stuck'
    | '/api/public/hooks/retention'
    | '/api/public/hooks/run-scheduled-broadcasts'
    | '/api/public/miniapp-proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicActionsStreamRoute: typeof ApiPublicActionsStreamRoute
  ApiPublicBulkStreamRoute: typeof ApiPublicBulkStreamRoute
  ApiPublicCleanupStreamRoute: typeof ApiPublicCleanupStreamRoute
  ApiPublicHooksAutoLeaveRoute: typeof ApiPublicHooksAutoLeaveRoute
  ApiPublicHooksDailySummaryRoute: typeof ApiPublicHooksDailySummaryRoute
  ApiPublicHooksResumeStuckRoute: typeof ApiPublicHooksResumeStuckRoute
  ApiPublicHooksRetentionRoute: typeof ApiPublicHooksRetentionRoute
  ApiPublicHooksRunScheduledBroadcastsRoute: typeof ApiPublicHooksRunScheduledBroadcastsRoute
  ApiPublicMiniappProxySplatRoute: typeof ApiPublicMiniappProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watchlists': {
      id: '/_authenticated/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof AuthenticatedWatchlistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stealth': {
      id: '/_authenticated/stealth'
      path: '/stealth'
      fullPath: '/stealth'
      preLoaderRoute: typeof AuthenticatedStealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proxies': {
      id: '/_authenticated/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof AuthenticatedProxiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile-updater': {
      id: '/_authenticated/profile-updater'
      path: '/profile-updater'
      fullPath: '/profile-updater'
      preLoaderRoute: typeof AuthenticatedProfileUpdaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join-pacing': {
      id: '/_authenticated/join-pacing'
      path: '/join-pacing'
      fullPath: '/join-pacing'
      preLoaderRoute: typeof AuthenticatedJoinPacingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cleanup': {
      id: '/_authenticated/cleanup'
      path: '/cleanup'
      fullPath: '/cleanup'
      preLoaderRoute: typeof AuthenticatedCleanupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/captcha': {
      id: '/_authenticated/captcha'
      path: '/captcha'
      fullPath: '/captcha'
      preLoaderRoute: typeof AuthenticatedCaptchaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulk-plus': {
      id: '/_authenticated/bulk-plus'
      path: '/bulk-plus'
      fullPath: '/bulk-plus'
      preLoaderRoute: typeof AuthenticatedBulkPlusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulk-mix': {
      id: '/_authenticated/bulk-mix'
      path: '/bulk-mix'
      fullPath: '/bulk-mix'
      preLoaderRoute: typeof AuthenticatedBulkMixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot-success': {
      id: '/_authenticated/bot-success'
      path: '/bot-success'
      fullPath: '/bot-success'
      preLoaderRoute: typeof AuthenticatedBotSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot-flow': {
      id: '/_authenticated/bot-flow'
      path: '/bot-flow'
      fullPath: '/bot-flow'
      preLoaderRoute: typeof AuthenticatedBotFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actions': {
      id: '/_authenticated/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AuthenticatedActionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cleanup-stream': {
      id: '/api/public/cleanup-stream'
      path: '/api/public/cleanup-stream'
      fullPath: '/api/public/cleanup-stream'
      preLoaderRoute: typeof ApiPublicCleanupStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bulk-stream': {
      id: '/api/public/bulk-stream'
      path: '/api/public/bulk-stream'
      fullPath: '/api/public/bulk-stream'
      preLoaderRoute: typeof ApiPublicBulkStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/actions-stream': {
      id: '/api/public/actions-stream'
      path: '/api/public/actions-stream'
      fullPath: '/api/public/actions-stream'
      preLoaderRoute: typeof ApiPublicActionsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks/new': {
      id: '/_authenticated/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthenticatedTasksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$id': {
      id: '/_authenticated/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AuthenticatedTasksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$id': {
      id: '/_authenticated/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AuthenticatedGroupsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/$id': {
      id: '/_authenticated/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthenticatedAccountsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/miniapp-proxy/$': {
      id: '/api/public/miniapp-proxy/$'
      path: '/api/public/miniapp-proxy/$'
      fullPath: '/api/public/miniapp-proxy/$'
      preLoaderRoute: typeof ApiPublicMiniappProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-scheduled-broadcasts': {
      id: '/api/public/hooks/run-scheduled-broadcasts'
      path: '/api/public/hooks/run-scheduled-broadcasts'
      fullPath: '/api/public/hooks/run-scheduled-broadcasts'
      preLoaderRoute: typeof ApiPublicHooksRunScheduledBroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/retention': {
      id: '/api/public/hooks/retention'
      path: '/api/public/hooks/retention'
      fullPath: '/api/public/hooks/retention'
      preLoaderRoute: typeof ApiPublicHooksRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resume-stuck': {
      id: '/api/public/hooks/resume-stuck'
      path: '/api/public/hooks/resume-stuck'
      fullPath: '/api/public/hooks/resume-stuck'
      preLoaderRoute: typeof ApiPublicHooksResumeStuckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-summary': {
      id: '/api/public/hooks/daily-summary'
      path: '/api/public/hooks/daily-summary'
      fullPath: '/api/public/hooks/daily-summary'
      preLoaderRoute: typeof ApiPublicHooksDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-leave': {
      id: '/api/public/hooks/auto-leave'
      path: '/api/public/hooks/auto-leave'
      fullPath: '/api/public/hooks/auto-leave'
      preLoaderRoute: typeof ApiPublicHooksAutoLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActionsRoute: typeof AuthenticatedActionsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBotFlowRoute: typeof AuthenticatedBotFlowRoute
  AuthenticatedBotSuccessRoute: typeof AuthenticatedBotSuccessRoute
  AuthenticatedBulkMixRoute: typeof AuthenticatedBulkMixRoute
  AuthenticatedBulkPlusRoute: typeof AuthenticatedBulkPlusRoute
  AuthenticatedCaptchaRoute: typeof AuthenticatedCaptchaRoute
  AuthenticatedCleanupRoute: typeof AuthenticatedCleanupRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedJoinPacingRoute: typeof AuthenticatedJoinPacingRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
  AuthenticatedProfileUpdaterRoute: typeof AuthenticatedProfileUpdaterRoute
  AuthenticatedProxiesRoute: typeof AuthenticatedProxiesRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedStealthRoute: typeof AuthenticatedStealthRoute
  AuthenticatedWatchlistsRoute: typeof AuthenticatedWatchlistsRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedAccountsIdRoute: typeof AuthenticatedAccountsIdRoute
  AuthenticatedGroupsIdRoute: typeof AuthenticatedGroupsIdRoute
  AuthenticatedTasksIdRoute: typeof AuthenticatedTasksIdRoute
  AuthenticatedTasksNewRoute: typeof AuthenticatedTasksNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActionsRoute: AuthenticatedActionsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBotFlowRoute: AuthenticatedBotFlowRoute,
  AuthenticatedBotSuccessRoute: AuthenticatedBotSuccessRoute,
  AuthenticatedBulkMixRoute: AuthenticatedBulkMixRoute,
  AuthenticatedBulkPlusRoute: AuthenticatedBulkPlusRoute,
  AuthenticatedCaptchaRoute: AuthenticatedCaptchaRoute,
  AuthenticatedCleanupRoute: AuthenticatedCleanupRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedJoinPacingRoute: AuthenticatedJoinPacingRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
  AuthenticatedProfileUpdaterRoute: AuthenticatedProfileUpdaterRoute,
  AuthenticatedProxiesRoute: AuthenticatedProxiesRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedStealthRoute: AuthenticatedStealthRoute,
  AuthenticatedWatchlistsRoute: AuthenticatedWatchlistsRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedAccountsIdRoute: AuthenticatedAccountsIdRoute,
  AuthenticatedGroupsIdRoute: AuthenticatedGroupsIdRoute,
  AuthenticatedTasksIdRoute: AuthenticatedTasksIdRoute,
  AuthenticatedTasksNewRoute: AuthenticatedTasksNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicActionsStreamRoute: ApiPublicActionsStreamRoute,
  ApiPublicBulkStreamRoute: ApiPublicBulkStreamRoute,
  ApiPublicCleanupStreamRoute: ApiPublicCleanupStreamRoute,
  ApiPublicHooksAutoLeaveRoute: ApiPublicHooksAutoLeaveRoute,
  ApiPublicHooksDailySummaryRoute: ApiPublicHooksDailySummaryRoute,
  ApiPublicHooksResumeStuckRoute: ApiPublicHooksResumeStuckRoute,
  ApiPublicHooksRetentionRoute: ApiPublicHooksRetentionRoute,
  ApiPublicHooksRunScheduledBroadcastsRoute:
    ApiPublicHooksRunScheduledBroadcastsRoute,
  ApiPublicMiniappProxySplatRoute: ApiPublicMiniappProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
