
CREATE TABLE public.inline_button_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid(),
  run_id UUID REFERENCES public.action_runs(id) ON DELETE SET NULL,
  account_id UUID REFERENCES public.telegram_accounts(id) ON DELETE SET NULL,
  peer_key TEXT,
  target TEXT,
  msg_id BIGINT,
  button_kind TEXT NOT NULL,
  button_label TEXT,
  button_payload TEXT,
  source TEXT NOT NULL DEFAULT 'viewer',
  result_status TEXT NOT NULL DEFAULT 'ok',
  result_message TEXT,
  result_alert BOOLEAN NOT NULL DEFAULT false,
  result_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ibc_user_time ON public.inline_button_clicks (user_id, created_at DESC);
CREATE INDEX idx_ibc_run ON public.inline_button_clicks (run_id);
CREATE INDEX idx_ibc_account ON public.inline_button_clicks (account_id, created_at DESC);

GRANT SELECT, INSERT ON public.inline_button_clicks TO authenticated;
GRANT ALL ON public.inline_button_clicks TO service_role;

ALTER TABLE public.inline_button_clicks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can read inline_button_clicks"
  ON public.inline_button_clicks FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Users can insert their own inline_button_clicks"
  ON public.inline_button_clicks FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);
